name: Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v7
      
    - name: Versions
      shell: bash
      run: |
        rustup --version
        cargo --version
        rustc --version

    - name: Cache
      uses: actions/cache@v6
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build [Debug]
      shell: bash
      run: LUA_LIB_NAME=lib/lua5.1 LUA_LINK=cdylib cargo build --verbose
      
    - name: Build [Release]
      shell: bash
      run: LUA_LIB_NAME=lib/lua5.1 LUA_LINK=cdylib cargo build --verbose --release
      
      # TODO: Ship required Lua files:
      # - amax/init.lua
      # - amax/init.luac
      # - amax/plugins/loader.lua (optional)
      # - amax/plugins/*/*.lua (optional)
    - name: Create zips
      shell: bash
      run: |
        python3 - <<'!EOF'
        from zipfile import ZipFile, ZIP_DEFLATED

        with ZipFile("lua-loader-debug.zip", "w", compression=ZIP_DEFLATED) as zf:
            zf.write("./target/i686-pc-windows-msvc/debug/lua_hooks.dll", "amax/dlls/lua_hooks.dll")
            zf.write("./target/i686-pc-windows-msvc/debug/lua_hooks.pdb", "amax/dlls/lua_hooks.pdb")

        with ZipFile("lua-loader-release.zip", "w", compression=ZIP_DEFLATED) as zf:
            zf.write("./target/i686-pc-windows-msvc/release/lua_hooks.dll", "amax/dlls/lua_hooks.dll")
        !EOF
      
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: windows-build
        path: |
          ./lua-loader-debug.zip
          ./lua-loader-release.zip

    - name: Publish to GitHub releases
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash
      run: |
        gh release create "${EPOCHREALTIME}-build-${GITHUB_SHA}" \
          ./lua-loader-debug.zip \
          ./lua-loader-release.zip \
          --title "$TAG" \
          --notes "Automated build artifacts" \
          --prerelease
